export enum DistributionPeriodStatus {
  DRAFT = 'DRAFT',
  RECIPIENTS_IMPORTED = 'RECIPIENTS_IMPORTED',
  PACKAGE_DEFINED = 'PACKAGE_DEFINED',
  INVOICED = 'INVOICED',
  ARCHIVED = 'ARCHIVED',
  CANCELED = 'CANCELED',
}
